### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by climentjoan** [bpapin19/wardle#1]
Hi there!

I'm Joan, and I'm working on an open source free teaching tool called FantasyClass: https://github.com/climentjoan/fantasyclass

I would like to add your wardle code into my app, to give the students rewards if they guess the teacher's words.

I've looked for the licence, but I didn't find it, I'll be very pleased if you tell me what licence do you have for this code, or if you give me the permission to use the code (it'll be recognized in my github repository).

Thank you so much!

**Comment by bpapin19** [comment]
Hey Joan!

Yes by all means incorporate my code into your app. There's no license or anything, I just wrote it to practice my Vue skills before I started a new job and as something fun to show my friends. However, I'm not sure if you're familiar with the game Wordle on New York Times, but I basically cloned all the functionality of it, with the exception of being able to play multiple times with custom words. Thanks for reaching out!

Best

**Comment by climentjoan** [comment]
Yes! I'm familiar with Wordle, I was looking for a Vue implementation of it, in Vue 2 or easy to migrate. I need the base to implement my own version, that will be integrated in FantasyClass.

Thank you so much! :) You've saved me a lot of time ^^

Best regards
